name: classes-testing

on:
  push:
    paths:
      - 'src/**/*.java'
      - 'test/**/*.java'

jobs:
  java-test:
    name: Check if the lib can still build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: install maven
        uses: s4u/setup-maven-action@v1.3.1
        with:
          java-version: 17
          maven-version: 3.8.4

      - name: check build
        run: mvn clean install
